### ISSUE TITLE
Following a link from a person to a show they are in 404's

### ISSUE THREAD

**Issue by backache** [salimfadhley/uk_improv_guide#15]
When following a link from a person's profile to a show they are in 404's

http://improv.guide:8000/performers/10

![image](https://user-images.githubusercontent.com/6274724/60420999-d5980480-9be0-11e9-8a4d-35f743cd1e61.png)

Clicking on "Moop presents" 404's

![image](https://user-images.githubusercontent.com/6274724/60421085-011aef00-9be1-11e9-9322-6a05b7674b6d.png)

**Comment by salimfadhley** [comment]
I think this has been fixed now, thanks!
